apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: task-manager
  namespace: argocd

spec:
  description: Task Manager GitOps Project

  sourceRepos:
    - https://github.com/AryanAtel1034/fuildAi-Assesment.git

  destinations:
    - namespace: task-manager-dev
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
